### ISSUE TITLE
Lab 1

### ISSUE THREAD

**Issue by rlnesbit** [idc9/stor390#3]
Most notably, 

1. "Quesetion" should be "Question" (appears several times)
2. In "Quesetion 5": 

> Create a data frame called radio_dept whose rows are the employees from the Radiology department. include only the followig columns: name, position, age, nonstsal, salary. order the employees by salary

There is no variable called salary, but there is a "stsal" and "totalsal." I assume in this question salary refers to "totalsal"?

**Comment by idc9** [comment]
1. Good catch

2. yes I meant totalsal
