### ISSUE TITLE
an extra "`"?

### ISSUE THREAD

**Issue by keithpjolley** [idc9/stor390#48]
Hi - 
Sorry, new to RStudio so maybe it's my understanding that's an issue. Anyways, lines 101 through 108 of "cross_validation.Rmd" are:

> 101: ````{r}
> 102: # the mixture means should be the same for both training and test sets
> 103: mean_seed <- 238
> 104: 
> 105: # draw train and test data
> 106: data <- gmm_distribution2d(n_neg=200, n_pos=201, mean_seed=mean_seed, data_seed=1232)
> 107: test_data <- gmm_distribution2d(n_neg=1000, n_pos=1000, mean_seed=mean_seed, data_seed=52345)
> 108: ```
 

I think it 101 should only have three "`" in it to match line 108.
Thanks -
Keith

**Comment by idc9** [comment]
It probably should be 3, but it seems to compile with 4 so I guess Rmd isn't too picky about this.

**Comment by keithpjolley** [comment]
RStudio is picky though.
